name = "LazyFym"
uuid = "19ce2a37-d051-4e03-9a1e-989d2d09a817"
authors = ["JinraeKim <kjl950403@gmail.com> and contributors"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[compat]
Parameters = "0.12"
Transducers = "0.4"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
