name = "LazyFym"
uuid = "19ce2a37-d051-4e03-9a1e-989d2d09a817"
authors = ["JinraeKim <kjl950403@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
